title: "Marco Haruni"
email: "marcoharuni95@gmail.com"
description: "AI Researcher, Engineer, and Writer"
baseurl: ""
url: "https://marcoharuni.github.io"
github_username: "marcoharuni"
markdown: kramdown
theme: minima
permalink: /:title/
